services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leetcode-bot
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
